apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mysql-requirements
spec:
  capacity:
    storage: 1.5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard-requirements
  volumeMode: Filesystem
  local:
    path: /mnt/data/mysql/mysql2  # Ensure this path exists on the target node
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - vm  # Replace with actual node name

