apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mysql-uml
spec:
  capacity:
    storage: 1.5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard-uml
  volumeMode: Filesystem
  #local:
   # path: /mnt/data/mysql/mysql3  # Ensure this path exists on the target node
 # nodeAffinity:
  #  required:
   #   nodeSelectorTerms:
    #    - matchExpressions:
     #       - key: kubernetes.io/hostname
      #        operator: In
       #       values:
        #        - vm  # Replace with your actual node name
  iscsi:
    targetPortal: 10.10.3.113:3260           # Use the IP of your iSCSI target
    iqn: iqn.2025-06.com.example:uml
    lun: 0
    fsType: ext4
    readOnly: false
    
