apiVersion: v1
kind: Pod
metadata:
  name: uml-reader
spec:
  nodeSelector:
    kubernetes.io/hostname: master
  restartPolicy: Always
  containers:
    - name: reader
      image: busybox
      command:
        - /bin/sh
      args:
        - -c
        - |
          cd /mnt
          while true; do
            echo "Scanning at $(date)"
            find . -type f -exec dd if={} of=/dev/null bs=4K count=1 iflag=direct \; 2>/dev/null
            sleep 15
          done
      volumeMounts:
        - name: uml-storage
          mountPath: /mnt
      securityContext:
        runAsUser: 999
        runAsGroup: 999
        allowPrivilegeEscalation: false
  volumes:
    - name: uml-storage
      persistentVolumeClaim:
        claimName: uml-mysql-pvc

