apiVersion: v1
kind: Secret
metadata:
  name: requirements-mysql-secret
type: Opaque
stringData:
  MYSQL_USER: {{ .Values.requirements.mysql.user }}
  MYSQL_PASSWORD: {{ .Values.requirements.mysql.password }}
  MYSQL_ROOT_PASSWORD: {{ .Values.requirements.mysql.rootPassword }}
