apiVersion: apps/v1
kind: Deployment
metadata:
  name: requirements-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: requirements-mysql
  template:
    metadata:
      labels:
        app: requirements-mysql
    spec:
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: requirements-mysql-pvc

        # Mounts the configmap containing init SQL
        - name: init-sql
          configMap:
            name: requirements-mysql-initdb-config

        # Scratch space to hold SQL before container startup
        - name: mysql-initdb
          emptyDir: {}

      initContainers:
        - name: init-mysql
          image: busybox
          command: ["sh", "-c", "cp /init/requirements-schema.sql /initdb/requirements-schema.sql"]
          volumeMounts:
            - name: init-sql
              mountPath: /init
            - name: mysql-initdb
              mountPath: /initdb

      containers:
        - name: mysql
          image: mysql:8.0
          env:
            - name: MYSQL_DATABASE
              value: {{ .Values.requirements.mysql.database }}
            - name: MYSQL_USER
              value: {{ .Values.requirements.mysql.user }}
            - name: MYSQL_PASSWORD
              value: {{ .Values.requirements.mysql.password }}
            - name: MYSQL_ROOT_PASSWORD
              value: {{ .Values.requirements.mysql.rootPassword }}
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
            - name: mysql-initdb
              mountPath: /docker-entrypoint-initdb.d

