apiVersion: v1
kind: Service
metadata:
  name: requirements-service
  labels:
    app: vmodel-visualizer
    component: requirements
spec:
  selector:
    app: vmodel
    component: requirements
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  type: ClusterIP
