apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
stringData:
  MYSQL_USER: {{ .Values.mysql.user }}
  MYSQL_PASSWORD: {{ .Values.mysql.password }}
  MYSQL_ROOT_PASSWORD: {{ .Values.mysql.rootPassword }}
