apiVersion: v1
kind: Secret
metadata:
  name: uml-backend-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  username: {{ .Values.uml.mysql.user | b64enc }}
  password: {{ .Values.uml.mysql.password | b64enc }}
  database: {{ .Values.uml.mysql.database | b64enc }}
  host: {{ "uml-mysql-service" | b64enc }}

