apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uml-mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.uml.persistence.size }}
  storageClassName: standard-uml
