apiVersion: apps/v1
kind: Deployment
metadata:
  name: uml-backend-deployment
  labels:
    app: vmodel-visualizer
    component: uml-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vmodel-visualizer
      component: uml-backend
  template:
    metadata:
      labels:
        app: vmodel-visualizer
        component: uml-backend
    spec:
      containers:
        - name: uml-backend-container
          image: pes1202201364/uml-diagram-backend
          ports:
            - containerPort: 3000
          env:
            - name: DB_HOST
              value: "uml-mysql-service"
            - name: DB_PORT
              value: "3306"
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: uml-backend-secret
                  key: database
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: uml-backend-secret
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: uml-backend-secret
                  key: password
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10

