apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb-config
data:
  database.sql: |
    CREATE TABLE IF NOT EXISTS users (
      id INT AUTO_INCREMENT PRIMARY KEY,
      name VARCHAR(255),
      email VARCHAR(255)
    );
    INSERT INTO users (name, email) VALUES ('John Doe', 'john@example.com');
