apiVersion: v1
kind: Service
metadata:
  name: uml-service
  labels:
    app: vmodel-visualizer
    component: uml
spec:
  selector:
    app: vmodel-visualizer
    component: uml
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: ClusterIP
