apiVersion: v1
kind: ConfigMap
metadata:
  name: vmodel-nginx-config
  namespace: {{ .Release.Namespace }}
data:
  default.conf: |
    upstream backend {
        server vmodel-service:80;
    }

    server {
        listen 80;
        location / {
            proxy_pass http://backend;
        }
    }

