nodeExporter:
  extraArgs:
    - "--collector.textfile.directory=/textfile-collector"

  hostRootFsMount: false

  extraHostPathMounts:
    - name: textfile-metrics
      hostPath: /var/lib/node_exporter/textfile_collector
      mountPath: /textfile-collector
      readOnly: false

