apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: requirements-mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.requirements.persistence.size }}
  storageClassName: standard-requirements
