apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vmodel-visualizer-lab.fullname" . }}-requirements
  labels:
    app: {{ include "vmodel-visualizer-lab.name" . }}
    component: requirements
spec:
  replicas: {{ .Values.requirementsService.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "vmodel-visualizer-lab.name" . }}
      component: requirements
  template:
    metadata:
      labels:
        app: {{ include "vmodel-visualizer-lab.name" . }}
        component: requirements
    spec:
      containers:
        - name: requirements
          image: pes1202201364/requirements-manager:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.requirementsService.port }}
          env:
            {{- range .Values.requirementsService.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
          resources:
            {{- toYaml .Values.requirementsService.resources | nindent 12 }}
