apiVersion: apps/v1
kind: Deployment
metadata:
  name: uml-deployment
  labels:
    app: vmodel-visualizer
    component: uml
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vmodel-visualizer
      component: uml
  template:
    metadata:
      labels:
        app: vmodel-visualizer
        component: uml
    spec:
      containers:
        - name: uml-container
          image: pes1202201364/uml-diagram:latest
          ports:
            - containerPort: 8000
          env:
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: DATABASE_URL
              value: "mysql://{{ .Values.uml.mysql.user }}:{{ .Values.uml.mysql.password }}@uml-mysql-service:3306/{{ .Values.uml.mysql.database }}"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          readinessProbe:
            httpGet:
              path: /docs
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /docs
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
