apiVersion: v1
kind: Service
metadata:
  name: uml-backend-service
  labels:
    app: vmodel-visualizer
    component: uml-backend
spec:
  selector:
    app: vmodel-visualizer
    component: uml-backend
  ports:
    - name: http
      port: 3000
      targetPort: 3000
  type: ClusterIP

