apiVersion: apps/v1
kind: Deployment
metadata:
  name: uml-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uml-mysql
  template:
    metadata:
      labels:
        app: uml-mysql
    spec:
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: uml-mysql-pvc

        - name: init-sql
          configMap:
            name: uml-mysql-initdb-config

        - name: mysql-initdb
          emptyDir: {}

      initContainers:
        - name: init-mysql
          image: busybox
          command: ["sh", "-c", "cp /init/uml-schema.sql /initdb/uml-schema.sql"]
          volumeMounts:
            - name: init-sql
              mountPath: /init
            - name: mysql-initdb
              mountPath: /initdb

      containers:
        - name: mysql
          image: mysql:8.0
          env:
            - name: MYSQL_DATABASE
              value: {{ .Values.uml.mysql.database }}
            - name: MYSQL_USER
              value: {{ .Values.uml.mysql.user }}
            - name: MYSQL_PASSWORD
              value: {{ .Values.uml.mysql.password }}
            - name: MYSQL_ROOT_PASSWORD
              value: {{ .Values.uml.mysql.rootPassword }}
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
            - name: mysql-initdb
              mountPath: /docker-entrypoint-initdb.d

