mysql:
  user: vmodeluser
  password: supersecret
  rootPassword: rootsecret
  database: vmodel

persistence:
  size: 1.5Gi

vmodel:
  image: pes1202201364/vmodel-api:latest
  replicas: 1


uml:
  mysql:
    user: umluser
    password: umlpass
    rootPassword: umlroot
    database: uml
  persistence:
    size: 1.5Gi


requirements:
  mysql:
    user: requser
    password: reqpass
    rootPassword: reqroot
    database: requirementsdb
  persistence:
    size: 1.5Gi

requirementsService:
  replicaCount: 1
  port: 8000
  env:
    - name: DATABASE_URL
      value: mysql://requser:reqpass@requirements-mysql-service:3306/requirementsdb
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"
